/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SearchRouteImport } from './routes/search'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as MapRouteImport } from './routes/map'
import { Route as LotteriesRouteImport } from './routes/lotteries'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as BrowseRouteImport } from './routes/browse'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BuildingBuildingIdRouteImport } from './routes/building.$buildingId'
import { Route as BoroughBoroughSlugRouteImport } from './routes/borough.$boroughSlug'

const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const LotteriesRoute = LotteriesRouteImport.update({
  id: '/lotteries',
  path: '/lotteries',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const BrowseRoute = BrowseRouteImport.update({
  id: '/browse',
  path: '/browse',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BuildingBuildingIdRoute = BuildingBuildingIdRouteImport.update({
  id: '/building/$buildingId',
  path: '/building/$buildingId',
  getParentRoute: () => rootRouteImport,
} as any)
const BoroughBoroughSlugRoute = BoroughBoroughSlugRouteImport.update({
  id: '/borough/$boroughSlug',
  path: '/borough/$boroughSlug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/browse': typeof BrowseRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/lotteries': typeof LotteriesRoute
  '/map': typeof MapRoute
  '/pricing': typeof PricingRoute
  '/search': typeof SearchRoute
  '/borough/$boroughSlug': typeof BoroughBoroughSlugRoute
  '/building/$buildingId': typeof BuildingBuildingIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/browse': typeof BrowseRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/lotteries': typeof LotteriesRoute
  '/map': typeof MapRoute
  '/pricing': typeof PricingRoute
  '/search': typeof SearchRoute
  '/borough/$boroughSlug': typeof BoroughBoroughSlugRoute
  '/building/$buildingId': typeof BuildingBuildingIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/browse': typeof BrowseRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/lotteries': typeof LotteriesRoute
  '/map': typeof MapRoute
  '/pricing': typeof PricingRoute
  '/search': typeof SearchRoute
  '/borough/$boroughSlug': typeof BoroughBoroughSlugRoute
  '/building/$buildingId': typeof BuildingBuildingIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/browse'
    | '/dashboard'
    | '/login'
    | '/lotteries'
    | '/map'
    | '/pricing'
    | '/search'
    | '/borough/$boroughSlug'
    | '/building/$buildingId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/browse'
    | '/dashboard'
    | '/login'
    | '/lotteries'
    | '/map'
    | '/pricing'
    | '/search'
    | '/borough/$boroughSlug'
    | '/building/$buildingId'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/browse'
    | '/dashboard'
    | '/login'
    | '/lotteries'
    | '/map'
    | '/pricing'
    | '/search'
    | '/borough/$boroughSlug'
    | '/building/$buildingId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BrowseRoute: typeof BrowseRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  LotteriesRoute: typeof LotteriesRoute
  MapRoute: typeof MapRoute
  PricingRoute: typeof PricingRoute
  SearchRoute: typeof SearchRoute
  BoroughBoroughSlugRoute: typeof BoroughBoroughSlugRoute
  BuildingBuildingIdRoute: typeof BuildingBuildingIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lotteries': {
      id: '/lotteries'
      path: '/lotteries'
      fullPath: '/lotteries'
      preLoaderRoute: typeof LotteriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/browse': {
      id: '/browse'
      path: '/browse'
      fullPath: '/browse'
      preLoaderRoute: typeof BrowseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/building/$buildingId': {
      id: '/building/$buildingId'
      path: '/building/$buildingId'
      fullPath: '/building/$buildingId'
      preLoaderRoute: typeof BuildingBuildingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/borough/$boroughSlug': {
      id: '/borough/$boroughSlug'
      path: '/borough/$boroughSlug'
      fullPath: '/borough/$boroughSlug'
      preLoaderRoute: typeof BoroughBoroughSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BrowseRoute: BrowseRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  LotteriesRoute: LotteriesRoute,
  MapRoute: MapRoute,
  PricingRoute: PricingRoute,
  SearchRoute: SearchRoute,
  BoroughBoroughSlugRoute: BoroughBoroughSlugRoute,
  BuildingBuildingIdRoute: BuildingBuildingIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
